SECRET_KEY_JWT: my_secret_key
DB:
    POSTGRES_DB: apiyoutube
    POSTGRES_USER: apiyoutube
    POSTGRES_PASSWORD: password
    POSTGRES_PORT: 5432
    POSTGRES_HOST: 127.0.0.1
ENV: local

KAFKA_HOST: localhost:9092